import 'dart:math';

import 'package:flutter/material.dart';

class AnimalPage extends StatelessWidget {
  const AnimalPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    String animal = generateAnimal();

    return Scaffold(
      body: Container(
        color: Colors.red,
        child: Center(
          child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Flexible(
                child: Text(animal,
                    textAlign: TextAlign.center,
                    style: const TextStyle(
                        color: Colors.white,
                        fontSize: 70,
                        fontWeight: FontWeight.w700)),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

generateAnimal() {
  List<String> animals = [
    'Lion',
    'Tiger',
    'Elephant',
    'Giraffe',
    'Zebra',
    'Kangaroo',
    'Monkey',
    'Hippopotamus',
    'Panda',
    'Penguin',
    'Koala',
    'Gorilla',
    'Polar Bear',
    'Dolphin',
    'Whale',
    'Llama',
    'Ostrich',
    'Crocodile',
    'Jaguar',
    'Octopus',
    'Camel',
    'Koala',
    'Leopard',
    'Raccoon',
    'Sloth',
    'Squirrel',
    'Antelope',
    'Cheetah',
    'Puma',
    'Gazelle',
    'Bison',
    'Hedgehog',
    'Platypus',
    'Seahorse',
    'Starfish',
    'Chameleon',
    'Armadillo',
    'Duck',
    'Pigeon',
    'Parrot',
    'Seagull',
    'Flamingo',
    'Hummingbird',
    'Peacock',
    'Owl',
    'Swan',
    'Turkey',
    'Pelican',
    'Hawk',
    'Eagle',
    'Falcon',
    'Vulture',
    'Condor',
    'Woodpecker',
    'Roadrunner',
    'Raven',
    'Crow',
    'Magpie',
    'Sparrow',
    'Finch',
    'Canary',
    'Blue Jay',
    'Robin',
    'Cardinal',
    'Puffin',
    'Kiwi',
    'Cockatoo',
    'Toucan',
    'Pheasant',
    'Quail',
    'Ostrich',
    'Emu',
    'Cassowary',
    'Peafowl',
    'Goose',
    'Dodo',
    'Albatross',
    'Swift',
    'Bat',
    'Bee',
    'Ant',
    'Butterfly',
    'Dragonfly',
    'Ladybug',
    'Grasshopper',
    'Beetle',
    'Firefly',
    'Spider',
    'Scorpion',
    'Centipede',
    'Millipede',
    'Caterpillar',
    'Worm',
    'Snake',
    'Lizard',
    'Iguana',
    'Chameleon',
    'Turtle',
    'Tortoise',
    'Horse',
    'Cow',
    'Pig',
    'Sheep',
    'Goat',
    'Chicken',
    'Duck',
    'Rabbit',
    'Donkey',
    'Deer',
    'Fox',
    'Bear',
    'Wolf',
    'Coyote',
    'Hedgehog',
    'Raccoon',
    'Skunk',
    'Possum',
    'Beaver',
    'Rat',
    'Mouse',
    'Squirrel',
    'Hamster',
  ];

  Random random = Random();
  return animals[random.nextInt(animals.length)];
}
